import { hash } from "../kernel/stable.ts";
import type {
  EdgeTypeDefinition,
  MechanismDefinition,
  NodeTypeDefinition,
  WorldBlueprint,
  WorldSourceRecord,
} from "./types.ts";

const quantityField = { id: "quantity", valueType: "number" as const, required: true, causal: true, unit: "index" };

const placeType: NodeTypeDefinition = {
  id: "place",
  description: "A spatially located area with World-defined geography.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    { id: "terrain", valueType: "string", required: false, causal: true },
    { id: "climate", valueType: "string", required: false, causal: true },
    { id: "environmental-stress", valueType: "number", required: false, causal: true, unit: "index" },
    { id: "carrying-capacity", valueType: "number", required: false, causal: true, unit: "person" },
    { id: "accessibility", valueType: "number", required: false, causal: true, unit: "index" },
    { id: "map-x", valueType: "number", required: false, causal: false },
    { id: "map-y", valueType: "number", required: false, causal: false },
    { id: "image-path", valueType: "string", required: false, causal: false },
    { id: "image-caption", valueType: "string", required: false, causal: false },
  ],
};

const resourceStockType: NodeTypeDefinition = {
  id: "resource-stock",
  description: "A quantified stock whose changes must enter the causal ledger.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    quantityField,
    { id: "access-regime", valueType: "string", required: false, causal: true },
    { id: "capacity", valueType: "number", required: false, causal: true, unit: "index" },
    { id: "renewal-rate", valueType: "number", required: false, causal: true, unit: "index-per-year" },
    { id: "baseline-demand", valueType: "number", required: false, causal: true, unit: "index-per-year" },
    { id: "scarcity", valueType: "number", required: false, causal: true, unit: "ratio" },
    { id: "price-index", valueType: "number", required: false, causal: true, unit: "index" },
  ],
};

const personType: NodeTypeDefinition = {
  id: "person",
  description: "A perspective-bound subject; traits, motives, memories, roles, beliefs, and relationships are separate causal inputs.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    { id: "age", valueType: "number", required: false, causal: true, unit: "year" },
    { id: "focal", valueType: "boolean", required: false, causal: false },
    { id: "traits", valueType: "json", required: false, causal: true },
    { id: "wants", valueType: "json", required: false, causal: true },
    { id: "fears", valueType: "json", required: false, causal: true },
    { id: "needs", valueType: "json", required: false, causal: true },
    { id: "beliefs", valueType: "json", required: false, causal: true },
    { id: "narrative", valueType: "string", required: false, causal: true },
    { id: "memories", valueType: "json", required: false, causal: true },
    { id: "stress", valueType: "number", required: false, causal: true, unit: "index" },
    { id: "agency", valueType: "number", required: false, causal: true, unit: "index" },
    { id: "current-plan", valueType: "string", required: false, causal: true },
  ],
};

const organizationType: NodeTypeDefinition = {
  id: "organization",
  description: "A coordinated but internally plural actor with formal purpose, actual practices, coalitions, resources, and implementation chains.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    { id: "declared-goal", valueType: "string", required: true, causal: true },
    { id: "actual-practice", valueType: "string", required: true, causal: true },
    { id: "resources", valueType: "json", required: false, causal: true },
    { id: "culture", valueType: "json", required: false, causal: true },
    { id: "internal-coalitions", valueType: "json", required: false, causal: true },
    { id: "legitimacy", valueType: "number", required: false, causal: true, unit: "index" },
    { id: "cohesion", valueType: "number", required: false, causal: true, unit: "index" },
    { id: "capacity", valueType: "number", required: false, causal: true, unit: "index" },
    { id: "status", valueType: "string", required: false, causal: true },
  ],
};

const institutionType: NodeTypeDefinition = {
  id: "institution",
  description: "Formal rules, customs, enforcement, and rules-in-use bound to jurisdiction and time.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    { id: "formal-rule", valueType: "string", required: true, causal: true },
    { id: "rule-in-use", valueType: "string", required: true, causal: true },
    { id: "enforcement-capacity", valueType: "number", required: false, causal: true, unit: "index" },
  ],
};

const settlementType: NodeTypeDefinition = {
  id: "settlement",
  description: "A settlement whose population, infrastructure, and role may change over long history.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    { id: "population", valueType: "number", required: true, causal: true, unit: "person" },
    { id: "founded-year", valueType: "number", required: true, causal: true, unit: "year" },
    { id: "role", valueType: "string", required: true, causal: true },
    { id: "infrastructure-state", valueType: "string", required: false, causal: true },
    { id: "food-security", valueType: "number", required: false, causal: true, unit: "index" },
    { id: "migration-pressure", valueType: "number", required: false, causal: true, unit: "index" },
  ],
};

const hazardType: NodeTypeDefinition = {
  id: "hazard",
  description: "A potential disturbance whose realised damage depends on exposure and vulnerability.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    { id: "kind", valueType: "string", required: true, causal: true },
    { id: "baseline-frequency", valueType: "number", required: true, causal: true, unit: "per-century" },
    { id: "trigger-condition", valueType: "string", required: false, causal: true },
    { id: "severity-basis", valueType: "string", required: false, causal: true },
  ],
};

const routeType: NodeTypeDefinition = {
  id: "route",
  description: "A causal connection whose capacity, duration, reliability, access, and maintenance may change.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    { id: "origin", valueType: "reference", required: true, causal: true },
    { id: "destination", valueType: "reference", required: true, causal: true },
    { id: "capacity", valueType: "number", required: true, causal: true, unit: "index" },
    { id: "reliability", valueType: "number", required: true, causal: true, unit: "index" },
    { id: "travel-time", valueType: "number", required: true, causal: true, unit: "day" },
    { id: "maintenance", valueType: "number", required: true, causal: true, unit: "index" },
    { id: "status", valueType: "string", required: true, causal: true },
  ],
};

const populationGroupType: NodeTypeDefinition = {
  id: "population-group",
  description: "A low-resolution population with conserved count, livelihood, mobility, cohesion, and settlement potential.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    { id: "population", valueType: "number", required: true, causal: true, unit: "person" },
    { id: "livelihood", valueType: "string", required: true, causal: true },
    { id: "current-place", valueType: "reference", required: true, causal: true },
    { id: "mobility", valueType: "number", required: true, causal: true, unit: "index" },
    { id: "cohesion", valueType: "number", required: true, causal: true, unit: "index" },
    { id: "settlement-readiness", valueType: "number", required: true, causal: true, unit: "index" },
    { id: "settlement-name", valueType: "string", required: false, causal: false },
  ],
};

const eventType: NodeTypeDefinition = {
  id: "event",
  description: "A committed occurrence derived from prior state, with typed dimensions and participants rather than a plot instruction.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    { id: "category", valueType: "string", required: true, causal: true },
    { id: "start-time", valueType: "number", required: true, causal: true, unit: "world-time" },
    { id: "scale", valueType: "string", required: true, causal: true },
    { id: "status", valueType: "string", required: true, causal: true },
    { id: "intensity", valueType: "number", required: true, causal: true, unit: "index" },
    { id: "summary", valueType: "string", required: true, causal: false },
    { id: "dimensions", valueType: "json", required: true, causal: true },
    { id: "location-id", valueType: "reference", required: false, causal: true },
  ],
};

const worldIndicatorType: NodeTypeDefinition = {
  id: "world-indicator",
  description: "A derived cross-scale reconciliation surface; it feeds later mechanisms but never replaces detailed state.",
  fields: [
    { id: "name", valueType: "string", required: true, causal: false },
    ...["ecological-health", "resource-security", "economic-connectivity", "population-stability", "governance-legitimacy", "social-cohesion", "conflict-pressure"].map((id) => ({ id, valueType: "number" as const, required: true, causal: true, unit: "index" })),
    { id: "last-reconciled-time", valueType: "number", required: true, causal: true, unit: "world-time" },
  ],
};

const commonNodeTypes = [placeType, resourceStockType, personType, organizationType, institutionType, settlementType, hazardType, routeType, populationGroupType, eventType, worldIndicatorType] as const;

/** Shared installed ontology used by demo and creator-authored Worlds alike. */
export const genericWorldNodeTypes: readonly NodeTypeDefinition[] = commonNodeTypes;

function locatedIn(fromTypes: readonly string[]): EdgeTypeDefinition {
  return { id: "located-in", description: "Spatial containment.", fromTypes, toTypes: ["place"], fields: [] };
}

function commonEdgesFor(
  personExtras: readonly string[],
  spatialExtras: readonly string[],
  governedExtras: readonly string[],
): readonly EdgeTypeDefinition[] {
  const socialTypes = ["person", ...personExtras, "organization"];
  const affectableTypes = ["place", "resource-stock", "person", ...personExtras, "organization", "institution", "settlement", "hazard", "route", "population-group", ...spatialExtras];
  return [
    locatedIn(["resource-stock", "person", ...personExtras, "organization", "institution", "settlement", "hazard", "population-group", "event", ...spatialExtras]),
    { id: "member-of", description: "Perspective-bound membership or role.", fromTypes: ["person", ...personExtras], toTypes: ["organization"], fields: [{ id: "role", valueType: "string", required: true, causal: true }] },
    { id: "governs", description: "Formal or practical governance relationship.", fromTypes: ["organization", "institution"], toTypes: ["settlement", "resource-stock", ...governedExtras], fields: [{ id: "basis", valueType: "string", required: true, causal: true }] },
    { id: "related-to", description: "Directional social relationship with perspective-specific meaning.", fromTypes: socialTypes, toTypes: socialTypes, fields: [{ id: "relation", valueType: "string", required: true, causal: true }, { id: "trust", valueType: "number", required: false, causal: true, unit: "index" }] },
    { id: "exposed-to", description: "Exposure to a hazard; it does not itself assert damage.", fromTypes: ["settlement", "resource-stock", "person", ...personExtras, ...spatialExtras], toTypes: ["hazard"], fields: [{ id: "vulnerability", valueType: "number", required: true, causal: true, unit: "index" }] },
    { id: "affected-by", description: "A typed, realized impact path from an entity to a committed Event.", fromTypes: affectableTypes, toTypes: ["event"], fields: [{ id: "impact", valueType: "number", required: true, causal: true, unit: "index" }, { id: "channel", valueType: "string", required: true, causal: true }] },
    { id: "originates-from", description: "A formation lineage from a settlement to a population group.", fromTypes: ["settlement"], toTypes: ["population-group"], fields: [{ id: "share", valueType: "number", required: true, causal: true, unit: "ratio" }, { id: "reason", valueType: "string", required: true, causal: true }] },
    { id: "trades-with", description: "A directional exchange relation constrained by routes, institutions, scarcity, and organization.", fromTypes: ["settlement", "organization", "population-group"], toTypes: ["settlement", "organization", "population-group"], fields: [{ id: "capacity", valueType: "number", required: true, causal: true, unit: "index" }, { id: "reliability", valueType: "number", required: true, causal: true, unit: "index" }, { id: "price-spread", valueType: "number", required: true, causal: true, unit: "index" }] },
    { id: "succeeds", description: "An explicit organizational succession, transformation, split, or merger lineage.", fromTypes: ["organization"], toTypes: ["organization"], fields: [{ id: "mode", valueType: "string", required: true, causal: true }, { id: "continuity", valueType: "json", required: true, causal: true }] },
  ];
}

/** Shared installed relations for Worlds without extra actor or spatial types. */
export const genericWorldEdgeTypes: readonly EdgeTypeDefinition[] = commonEdgesFor([], [], []);

export const mechanismLibrary: readonly MechanismDefinition[] = [
  {
    id: "mechanism.resource-balance",
    version: "1",
    description: "Applies unit-checked stock changes while keeping physical quantity distinct from access and claims.",
    requiredNodeTypes: ["resource-stock"],
    requiredAssumptions: ["resources.quantified"],
    theoryPackRefs: ["theory.economy.stock-flow-claims@1"],
    actionKinds: ["adjust-node-number", "set-node-attribute", "adjust-edge-number", "set-edge-attribute", "assert-fact"],
    evidenceMaturity: "author-defined",
  },
  {
    id: "mechanism.world-evolution",
    version: "1",
    description: "Creates typed entities, relations, and facts through recorded causal proposals.",
    requiredNodeTypes: ["place"],
    requiredAssumptions: ["world.change-recorded"],
    actionKinds: ["create-node", "create-edge", "assert-fact", "set-node-attribute", "adjust-node-number", "adjust-edge-number", "set-edge-attribute"],
    evidenceMaturity: "author-defined",
  },
  {
    id: "mechanism.environment-cycle",
    version: "1",
    description: "Accumulates environmental pressure from duration, local resources, coupled-system feedback, and reproducible residual uncertainty.",
    requiredNodeTypes: ["place", "resource-stock"],
    requiredAssumptions: ["ecology.environment-affects-settlement"],
    theoryPackRefs: ["theory.ecology.coupled-systems@1"],
    actionKinds: ["set-node-attribute", "assert-fact"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.route-dynamics",
    version: "1",
    description: "Evolves route reliability and interruption from endpoints, environment, maintenance, control, and realized hazards.",
    requiredNodeTypes: ["route", "place"],
    requiredAssumptions: ["history.investments-can-constrain-later-options"],
    theoryPackRefs: ["theory.history.path-dependence@1", "theory.ecology.coupled-systems@1"],
    actionKinds: ["set-node-attribute", "assert-fact"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.population-dynamics",
    version: "1",
    description: "Balances births, deaths, migration pressure, subsistence, and settlement readiness without treating populations as scenery.",
    requiredNodeTypes: ["settlement", "population-group"],
    requiredAssumptions: ["ecology.environment-affects-settlement"],
    theoryPackRefs: ["theory.ecology.coupled-systems@1", "theory.history.path-dependence@1"],
    actionKinds: ["adjust-node-number", "set-node-attribute", "assert-fact"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.exchange-network",
    version: "1",
    description: "Derives exchange capacity, reliability, and price pressure from routes, scarcity, organizations, and enforcement.",
    requiredNodeTypes: ["route", "resource-stock", "organization"],
    requiredAssumptions: ["resources.quantified", "institutions.rules-and-practices"],
    theoryPackRefs: ["theory.economy.stock-flow-claims@1", "theory.institution.rules-in-use@1"],
    actionKinds: ["set-edge-attribute", "adjust-edge-number", "assert-fact"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.institution-adaptation",
    version: "1",
    description: "Keeps formal rule, rule-in-use, jurisdiction, enforcement capacity, and organizational support causally distinct.",
    requiredNodeTypes: ["institution", "organization"],
    requiredAssumptions: ["institutions.rules-and-practices"],
    theoryPackRefs: ["theory.institution.rules-in-use@1", "theory.history.path-dependence@1"],
    actionKinds: ["set-node-attribute", "assert-fact"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.information-diffusion",
    version: "1",
    description: "Turns events into perspective-bounded observations only through declared spatial, role, record, and communication paths.",
    requiredNodeTypes: ["person", "event"],
    requiredAssumptions: ["agents.bounded-information-processing"],
    theoryPackRefs: ["theory.psychology.bounded-cognition@1", "theory.organization.principal-agent@1"],
    actionKinds: ["assert-fact"],
    evidenceMaturity: "author-defined",
  },
  {
    id: "mechanism.relationship-dynamics",
    version: "1",
    description: "Updates directional trust and obligation from accessible conduct and relationship-specific evidence.",
    requiredNodeTypes: ["person", "organization"],
    requiredAssumptions: ["agents.bounded-information-processing"],
    theoryPackRefs: ["theory.social.social-identity@1", "theory.psychology.bounded-cognition@1"],
    actionKinds: ["set-edge-attribute", "adjust-edge-number", "assert-fact"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.conflict-dynamics",
    version: "1",
    description: "Creates conflict Events when incompatible claims, low trust, resource pressure, and weak resolution capacity become jointly active.",
    requiredNodeTypes: ["organization", "event", "resource-stock"],
    requiredAssumptions: ["organizations.delegated-authority", "resources.materially-rivalrous"],
    theoryPackRefs: ["theory.organization.principal-agent@1", "theory.institution.rules-in-use@1"],
    actionKinds: ["create-node", "create-edge", "assert-fact", "set-edge-attribute"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.actor-deliberation",
    version: "1",
    description: "Uses perspective-bounded traits, motives, roles, memory, belief, and situational pressure to propose—not dictate—behaviour.",
    requiredNodeTypes: ["person"],
    requiredAssumptions: ["agents.trait-psychology-applicable", "agents.bounded-information-processing"],
    theoryPackRefs: ["theory.psychology.big-five@1", "theory.psychology.bounded-cognition@1"],
    actionKinds: ["set-node-attribute", "assert-fact", "create-edge"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.organization-adaptation",
    version: "1",
    description: "Separates declared mission, coalition interests, decisions, implementation, and observed practice.",
    requiredNodeTypes: ["organization", "institution"],
    requiredAssumptions: ["organizations.delegated-authority", "institutions.rules-and-practices"],
    theoryPackRefs: ["theory.organization.principal-agent@1", "theory.institution.rules-in-use@1"],
    actionKinds: ["set-node-attribute", "assert-fact", "create-edge", "create-node", "adjust-edge-number", "set-edge-attribute"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.hazard-impact",
    version: "1",
    description: "Proposes hazard consequences from intensity, exposure, vulnerability, and response capacity across scales.",
    requiredNodeTypes: ["hazard", "settlement"],
    requiredAssumptions: ["ecology.environment-affects-settlement"],
    theoryPackRefs: ["theory.ecology.coupled-systems@1"],
    actionKinds: ["adjust-node-number", "set-node-attribute", "assert-fact", "create-edge", "adjust-edge-number", "set-edge-attribute", "create-node"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.creator-world-laws",
    version: "1",
    description: "Executes creator-authored coupling parameters as recorded World state without granting extensions direct commit authority.",
    requiredNodeTypes: ["world-parameters", "place"],
    requiredAssumptions: ["world.creator-parameters-causal"],
    actionKinds: ["set-node-attribute", "assert-fact"],
    evidenceMaturity: "author-defined",
  },
  {
    id: "mechanism.salt-water-governance",
    version: "1",
    description: "Salt Marsh-specific negotiation among hydrology, salt rights, jurisdiction, clan obligation, and emergency practice.",
    requiredNodeTypes: ["salt-pan", "organization", "institution"],
    requiredAssumptions: ["salt-marsh.separate-water-systems"],
    theoryPackRefs: ["theory.institution.rules-in-use@1", "theory.history.path-dependence@1"],
    actionKinds: ["adjust-node-number", "set-node-attribute", "assert-fact", "create-edge", "adjust-edge-number", "set-edge-attribute", "create-node"],
    evidenceMaturity: "scenario-calibrated",
  },
  {
    id: "mechanism.spirit-vein-circulation",
    version: "1",
    description: "玄霄九域专属的灵脉存量、再生、抽取与地貌反馈机制；灵气必须经由局部因果路径流动。",
    requiredNodeTypes: ["spirit-vein", "realm-gate-remnant", "resource-stock"],
    requiredAssumptions: ["xuanxiao.qi-is-local-stock-flow"],
    theoryPackRefs: ["theory.economy.stock-flow-claims@1", "theory.ecology.coupled-systems@1"],
    actionKinds: ["adjust-node-number", "set-node-attribute", "assert-fact", "create-edge"],
    evidenceMaturity: "author-defined",
  },
  {
    id: "mechanism.cultivation-breakthrough",
    version: "1",
    description: "依据功法适配、灵气、经脉、道心、经验与风险条件提出突破结果；境界提升不是叙事奖励。",
    requiredNodeTypes: ["cultivator", "cultivation-art", "hazard"],
    requiredAssumptions: ["xuanxiao.cultivation-requires-preconditions"],
    theoryPackRefs: ["theory.psychology.bounded-cognition@1", "theory.economy.stock-flow-claims@1"],
    actionKinds: ["adjust-node-number", "set-node-attribute", "assert-fact", "create-edge"],
    evidenceMaturity: "author-defined",
  },
  {
    id: "mechanism.sect-lineage-governance",
    version: "1",
    description: "把宗门戒律、功法传承、资源配额、师徒派系、公开使命与实际执行分开建模。",
    requiredNodeTypes: ["organization", "institution", "cultivation-art", "spirit-vein"],
    requiredAssumptions: ["xuanxiao.sects-have-layered-authority", "organizations.delegated-authority"],
    theoryPackRefs: ["theory.organization.principal-agent@1", "theory.institution.rules-in-use@1", "theory.history.path-dependence@1"],
    actionKinds: ["set-node-attribute", "set-edge-attribute", "adjust-edge-number", "assert-fact", "create-edge", "create-node"],
    evidenceMaturity: "exploratory",
  },
  {
    id: "mechanism.dao-oath-consequence",
    version: "1",
    description: "只在已声明的参与方、条款、见证、触发条件和执行范围内形成道誓后果，禁止把道誓当作全知读心术。",
    requiredNodeTypes: ["cultivator", "dao-oath"],
    requiredAssumptions: ["xuanxiao.dao-oaths-have-declared-scope"],
    theoryPackRefs: ["theory.institution.rules-in-use@1", "theory.psychology.bounded-cognition@1"],
    actionKinds: ["set-node-attribute", "assert-fact", "create-edge"],
    evidenceMaturity: "author-defined",
  },
];

function source(worldId: string, id: string, title: string, content: string): WorldSourceRecord {
  return { worldId, id, revision: "1", kind: "creator-note", title, content, contentHash: hash(content), provenance: [`creator:${worldId}`] };
}

export const saltMarshSources: readonly WorldSourceRecord[] = [
  source("world.salt-marsh", "source:premise", "盐泽初始设定", "盐泽位于封闭盐盆地。淡水来自彼此不连通的断层泉；盐、畜产、山矿和河谷粮食形成四向交换。聚落、宗族、制度与道路在长期灾害和贸易中共同演变。"),
  source("world.salt-marsh", "source:people", "人物与组织约束", "人会受性格、经历、信念、利益、角色和信息限制共同影响。组织的公开目标、内部联盟和实际行为可能不一致。法律与习俗必须绑定地区、时期和执行能力。"),
];

export const xuanxiaoSources: readonly WorldSourceRecord[] = [
  source("world.xuanxiao-nine-realms", "source:premise", "玄霄九域：天地与地理", "天衡崩裂后，玄霄大陆分为九域。山脉、河谷、凡人城镇、古道与残存域门围绕灵脉重新组织。灵气来自天地与地脉的局部循环，不是无穷背景能量；开采、封禁、污染和改道会改变储量、生态、聚落与权力中心。当前验收聚焦苍澜域，但其他八域只作为明确边界外的相邻背景存在。"),
  source("world.xuanxiao-nine-realms", "source:cultivation", "玄霄九域：修炼、天劫与神魂", "修炼境界依次包含锻体、引气、筑基、金丹、元婴等阶段。突破必须满足功法适配、灵气储备、经脉状态、经验和道心条件，仍可能失败并产生反噬；重大跃迁可能触发有条件的天劫。灵根影响效率而不决定命运。转世、夺舍、分魂、记忆继承与社会身份继承不是同一种人格连续性，必须分别记录。"),
  source("world.xuanxiao-nine-realms", "source:society", "玄霄九域：宗门、王朝与凡俗社会", "宗门、修真家族、凡人王朝、商盟与地方共同体共享又争夺土地、人口、道路、灵脉和合法性。戒律、国法、乡约与实际执行按辖区和时期分层。组织的公开使命、长老派系、执行者利益与真实后果可以不一致；普通人是生产、迁徙、信仰和政治反馈的参与者，不是修士故事的布景。"),
  source("world.xuanxiao-nine-realms", "source:people", "玄霄九域：苍澜域初始局势", "玄历六百一十二年，太玄剑宗以守护苍澜灵脉为名，与大晟王朝共同执行《苍澜分脉约》，灵溪坊商盟负责部分配额交换。近二十年灵脉实测储量下降，宗门却维持扩招。勘脉弟子沈清洛发现账册与地脉回声不符；她敬重的师父陆玄机可能参与过旧数据封存。她必须在宗门忠诚、苍澜百姓的长期风险、个人前途和可验证事实之间作出选择。"),
  source("world.xuanxiao-nine-realms", "source:causal-defaults", "玄霄九域：语义编译后的因果默认", "为闭合当前可执行因果：苍澜主脉年再生310灵气单位，太玄剑宗与灵溪坊配额上限合计228，向河谷生态和环境灵气的基准外流为120；配额用足时年净变化为负38。北麓天衡残门在玄历五七一年暴走后被封，常态不持续泄漏灵气，但每十二年与灵潮共振并使主脉稳定度下降9；只有处于共振年且稳定度低于65，灵潮逆涌才取得发生资格。当前玄历六一二年满足共振年条件，主脉共振前稳定度为61。逆涌发生后按各对象暴露路径分别结算：可用灵气骤减、主脉稳定度继续下降、暴露修士消耗灵气并可能加重经脉伤势、灵溪坊基础设施受损，不能用一个全局伤害值替代。主脉稳定度不线性缩放当前年再生；稳定度跌破50后，下一完整年度的再生率由310降至210，恢复到55以上并持续一个完整年度后才以每年25的速度恢复。分脉约签署后，职责主体故意阻断依法应互查的勘测记录，并据此提交无异结论，也属于苍澜不竭誓的声明触发范围；道誓仍不能读取思想或追溯签署前未知事实。"),
];

export const saltMarshBlueprint: WorldBlueprint = {
  worldId: "world.salt-marsh",
  id: "blueprint.main",
  version: "1",
  title: "盐泽",
  summary: "一个由断层淡水、盐业权利、四向贸易、宗族与分区制度共同形成并持续演变的前工业盆地世界。",
  sourceRefs: saltMarshSources.map((value) => value.id),
  temporalModel: { id: "time.linear-years-days", version: "1", kind: "linear", coordinateDescription: "One monotonic logical coordinate; scale is carried by Simulation Frames.", runtimeProfile: "linear-discrete-v1" },
  identityModel: { id: "identity.embodied-social-continuity", version: "1", principles: ["embodied continuity", "social identity may change without creating a new person", "organizations persist through versioned succession rules"] },
  causalityModel: { id: "causality.forward-local", version: "1", principles: ["effects require reachable prior causes", "information remains perspective-bound", "hazards require exposure to cause loss"] },
  assumptions: [
    "world.change-recorded", "resources.quantified", "resources.materially-rivalrous", "agents.trait-psychology-applicable",
    "agents.bounded-information-processing", "groups.social-categorization-possible", "organizations.delegated-authority",
    "institutions.rules-and-practices", "history.investments-can-constrain-later-options", "ecology.environment-affects-settlement",
    "salt-marsh.separate-water-systems",
  ],
  theoryPacks: [
    { id: "theory.psychology.big-five", version: "1", mode: "parameterized", parameters: { cultureCalibration: "salt-basin" } },
    { id: "theory.psychology.bounded-cognition", version: "1", mode: "enabled", parameters: {} },
    { id: "theory.social.social-identity", version: "1", mode: "enabled", parameters: {} },
    { id: "theory.organization.principal-agent", version: "1", mode: "enabled", parameters: {} },
    { id: "theory.institution.rules-in-use", version: "1", mode: "enabled", parameters: {} },
    { id: "theory.economy.stock-flow-claims", version: "1", mode: "enabled", parameters: {} },
    { id: "theory.history.path-dependence", version: "1", mode: "enabled", parameters: {} },
    { id: "theory.ecology.coupled-systems", version: "1", mode: "enabled", parameters: {} },
  ],
  nodeTypes: [...commonNodeTypes, {
    id: "salt-pan", description: "A Salt Marsh-specific productive, hydrological, and rights-bearing unit.", worldSpecific: true,
    fields: [
      { id: "name", valueType: "string", required: true, causal: false },
      { id: "water-access", valueType: "number", required: true, causal: true, unit: "index" },
      { id: "claim-holders", valueType: "json", required: true, causal: true },
    ],
  }],
  edgeTypes: commonEdgesFor([], ["salt-pan"], ["salt-pan"]),
  rules: [
    { id: "rule.separate-freshwater-systems", description: "Freshwater systems are hydrologically separate; access in one place does not imply access elsewhere.", invariant: true, provenance: ["source:premise"] },
    { id: "rule.rights-are-not-water", description: "A water or salt claim changes enforceable access, not physical stock by itself.", invariant: true, provenance: ["source:people"], enforcement: [{ kind: "field-write-authority", nodeTypes: ["resource-stock"], fieldId: "quantity", mechanismIds: ["mechanism.resource-balance", "mechanism.hazard-impact"] }] },
    {
      id: "rule.bounded-material-and-population-state",
      description: "Material stocks and populations cannot become negative; bounded indexes remain in their declared ranges.",
      invariant: true,
      provenance: ["framework:executable-invariants-v1"],
      enforcement: [
        { kind: "numeric-range", nodeTypes: ["resource-stock"], fieldId: "quantity", minimum: 0, maximumFieldId: "capacity" },
        { kind: "numeric-range", nodeTypes: ["settlement", "population-group"], fieldId: "population", minimum: 0 },
        { kind: "numeric-range", nodeTypes: ["place"], fieldId: "environmental-stress", minimum: 0, maximum: 100 },
        { kind: "numeric-range", nodeTypes: ["salt-pan"], fieldId: "water-access", minimum: 0, maximum: 100 },
      ],
    },
  ],
  mechanisms: [
    { id: "mechanism.resource-balance", version: "1", parameters: { conservation: true } },
    { id: "mechanism.world-evolution", version: "1", parameters: {} },
    { id: "mechanism.environment-cycle", version: "1", parameters: { residualUncertainty: "stable-random" } },
    { id: "mechanism.route-dynamics", version: "1", parameters: { adaptiveIntervals: true } },
    { id: "mechanism.population-dynamics", version: "1", parameters: { conservePopulationTransfers: true } },
    { id: "mechanism.exchange-network", version: "1", parameters: { routeAndScarcityBound: true } },
    { id: "mechanism.actor-deliberation", version: "1", parameters: { proposer: "deterministic" } },
    { id: "mechanism.organization-adaptation", version: "1", parameters: {} },
    { id: "mechanism.institution-adaptation", version: "1", parameters: {} },
    { id: "mechanism.information-diffusion", version: "1", parameters: { perspectiveBounded: true } },
    { id: "mechanism.relationship-dynamics", version: "1", parameters: { directional: true } },
    { id: "mechanism.conflict-dynamics", version: "1", parameters: { eventDriven: true } },
    { id: "mechanism.hazard-impact", version: "1", parameters: { stochasticHazards: true } },
    { id: "mechanism.salt-water-governance", version: "1", parameters: {} },
  ],
  initialGraph: {
    nodes: [
      { id: "place:central-basin", type: "place", attributes: { name: "盐泽中央盆地", terrain: "盐壳盆地与断层泉", climate: "强蒸发、季节暴雨", "environmental-stress": 37, "carrying-capacity": 7200, accessibility: 64 } },
      { id: "place:southern-road-gate", type: "place", attributes: { name: "南道泉驿带", terrain: "盐壳南缘的季节河沟与商路交汇", climate: "干热、多风、偶发暴雨", "environmental-stress": 43, "carrying-capacity": 1300, accessibility: 58 } },
      { id: "settlement:salt-marsh-town", type: "settlement", attributes: { name: "盐泽镇", population: 4200, "founded-year": 138, role: "泉口盐贸节点", "infrastructure-state": "泉门、盐仓与四向驿路维持运转", "food-security": 68, "migration-pressure": 31 } },
      { id: "resource:freshwater", type: "resource-stock", attributes: { name: "中央泉可用淡水", quantity: 100, "access-regime": "井券与应急配给并存", capacity: 120, "renewal-rate": 8.5, "baseline-demand": 10, scarcity: 0.1667, "price-index": 105 } },
      { id: "salt-pan:gu-rong", type: "salt-pan", attributes: { name: "顾荣盐台", "water-access": 45, "claim-holders": ["clan:gu", "organization:well-council"] } },
      { id: "population:southern-caravan-families", type: "population-group", attributes: { name: "南道季居商牧家庭", population: 360, livelihood: "驮运、畜养与临时修路", "current-place": "place:southern-road-gate", mobility: 67, cohesion: 61, "settlement-readiness": 72, "settlement-name": "南道泉驿" } },
      { id: "route:southern-road", type: "route", attributes: { name: "盐泽南道", origin: "place:central-basin", destination: "place:southern-road-gate", capacity: 62, reliability: 66, "travel-time": 4, maintenance: 54, status: "open-with-risk" } },
      { id: "person:mara", type: "person", attributes: { name: "玛拉", age: 38, traits: { conscientiousness: 78, agreeableness: 42 }, wants: ["keep the spring open"], fears: ["clan seizure"], needs: ["trust without surrender"], beliefs: ["institutions fail when nobody bears personal cost"], narrative: "I keep promises others turn into slogans.", memories: ["year-210 gate cooperation"], stress: 38, agency: 63, "current-plan": "维持泉门记录并观察宗族对旱情的反应" } },
      { id: "organization:well-council", type: "organization", attributes: { name: "泉议会", "declared-goal": "公平维护公共泉水", "actual-practice": "在宗族否决与紧急协商间分配井券", resources: ["water records", "gate keepers"], culture: ["public reasoning", "private bargaining"], "internal-coalitions": ["open-well bloc", "lineage veto bloc"], legitimacy: 57, cohesion: 52, capacity: 61, status: "active" } },
      { id: "institution:well-rights", type: "institution", attributes: { name: "分区井券法", "formal-rule": "井券按户与盐台登记", "rule-in-use": "旱季由守门人与宗族代表临时重排", "enforcement-capacity": 63 } },
      { id: "hazard:salt-storm", type: "hazard", attributes: { name: "盐尘暴", kind: "extreme-weather", "baseline-frequency": 8 } },
    ],
    edges: [
      { id: "edge:town-in-basin", type: "located-in", from: "settlement:salt-marsh-town", to: "place:central-basin", attributes: {} },
      { id: "edge:water-in-basin", type: "located-in", from: "resource:freshwater", to: "place:central-basin", attributes: {} },
      { id: "edge:pan-in-basin", type: "located-in", from: "salt-pan:gu-rong", to: "place:central-basin", attributes: {} },
      { id: "edge:mara-in-basin", type: "located-in", from: "person:mara", to: "place:central-basin", attributes: {} },
      { id: "edge:council-in-basin", type: "located-in", from: "organization:well-council", to: "place:central-basin", attributes: {} },
      { id: "edge:rights-in-basin", type: "located-in", from: "institution:well-rights", to: "place:central-basin", attributes: {} },
      { id: "edge:storm-in-basin", type: "located-in", from: "hazard:salt-storm", to: "place:central-basin", attributes: {} },
      { id: "edge:southern-families-at-road", type: "located-in", from: "population:southern-caravan-families", to: "place:southern-road-gate", attributes: {} },
      { id: "edge:mara-council", type: "member-of", from: "person:mara", to: "organization:well-council", attributes: { role: "守门记录官" } },
      { id: "edge:mara-council-trust", type: "related-to", from: "person:mara", to: "organization:well-council", attributes: { relation: "职责依赖与对宗族妥协的不满并存", trust: 53 } },
      { id: "edge:council-governs-water", type: "governs", from: "organization:well-council", to: "resource:freshwater", attributes: { basis: "分区井券法与实际守门权" } },
      { id: "edge:town-storm-exposure", type: "exposed-to", from: "settlement:salt-marsh-town", to: "hazard:salt-storm", attributes: { vulnerability: 54 } },
      { id: "edge:water-storm-exposure", type: "exposed-to", from: "resource:freshwater", to: "hazard:salt-storm", attributes: { vulnerability: 24 } },
      { id: "edge:town-southern-exchange", type: "trades-with", from: "settlement:salt-marsh-town", to: "population:southern-caravan-families", attributes: { capacity: 46, reliability: 58, "price-spread": 118 } },
    ],
    facts: [
      { id: "fact:freshwater-systems-separated", subjectId: "place:central-basin", predicate: "freshwater-system", value: "central-fault-spring", authority: "creator-confirmed", provenance: ["source:premise"], epistemicScope: "world" },
      { id: "fact:council-goal-practice-gap", subjectId: "organization:well-council", predicate: "mission-practice-gap", value: true, authority: "creator-confirmed", provenance: ["source:people"], epistemicScope: "world" },
    ],
  },
  presentationHints: { mapStyle: "large regional atlas", palette: "salt, ochre, indigo" },
};

export const xuanxiaoBlueprint: WorldBlueprint = {
  worldId: "world.xuanxiao-nine-realms",
  id: "blueprint.main",
  version: "1",
  title: "玄霄九域",
  summary: "天衡崩裂后的九域仙侠世界：灵脉、修炼、宗门、王朝与凡俗社会在可追溯的资源、制度、心理和历史因果中共同演化。",
  sourceRefs: xuanxiaoSources.map((value) => value.id),
  temporalModel: { id: "time.xuan-calendar-years-days", version: "1", kind: "linear", coordinateDescription: "玄历线性纪年；世纪、年、月、日尺度由 Simulation Frames 共同表达。", runtimeProfile: "linear-discrete-v1" },
  identityModel: {
    id: "identity.embodied-soul-social-continuity",
    version: "1",
    principles: [
      "肉身连续、神魂连续、记忆连续和社会身份连续分别记录",
      "转世、夺舍、分魂、化身与记忆继承不会自动判定为同一人格",
      "宗门与王朝通过有版本的继承、分裂、兼并和合法性规则延续",
    ],
  },
  causalityModel: {
    id: "causality.forward-local-qi",
    version: "1",
    principles: [
      "灵气、术法与神识只能沿世界规则允许的局部路径产生效果",
      "力量、境界和主角身份都不豁免资源、距离、信息与反制条件",
      "凡俗制度、集体行动与生态反馈与超凡机制同属可追溯因果",
    ],
  },
  assumptions: [
    "world.change-recorded", "resources.quantified", "resources.materially-rivalrous", "agents.trait-psychology-applicable",
    "agents.bounded-information-processing", "groups.social-categorization-possible", "organizations.delegated-authority",
    "institutions.rules-and-practices", "history.investments-can-constrain-later-options", "ecology.environment-affects-settlement",
    "xuanxiao.qi-is-local-stock-flow", "xuanxiao.cultivation-requires-preconditions",
    "xuanxiao.sects-have-layered-authority", "xuanxiao.dao-oaths-have-declared-scope",
    "xuanxiao.soul-continuity-must-be-declared",
  ],
  theoryPacks: [
    { id: "theory.psychology.big-five", version: "1", mode: "parameterized", parameters: { cultureCalibration: "sect-mortal-layered-society", lifespanCalibration: "realm-dependent", interpretation: "tendencies-not-destiny" } },
    { id: "theory.psychology.bounded-cognition", version: "1", mode: "parameterized", parameters: { supernaturalPerception: "rule-bounded", omniscience: false } },
    { id: "theory.social.social-identity", version: "1", mode: "parameterized", parameters: { categories: ["宗门", "师承", "境界", "家族", "凡人或修士", "地域"] } },
    { id: "theory.organization.principal-agent", version: "1", mode: "parameterized", parameters: { delegationLayers: ["掌门", "长老", "执事", "弟子", "外部附庸"] } },
    { id: "theory.institution.rules-in-use", version: "1", mode: "parameterized", parameters: { jurisdictions: ["宗门戒律", "王朝国法", "坊市契约", "地方乡约"] } },
    { id: "theory.economy.stock-flow-claims", version: "1", mode: "parameterized", parameters: { stocks: ["灵脉", "灵石", "丹药", "土地", "粮食", "寿元"], qiConservation: "local-with-renewal" } },
    { id: "theory.history.path-dependence", version: "1", mode: "parameterized", parameters: { longLivedIncumbents: true, ancientInfrastructure: true } },
    { id: "theory.ecology.coupled-systems", version: "1", mode: "parameterized", parameters: { supernaturalEcology: "spirit-vein-coupled" } },
  ],
  nodeTypes: [
    ...commonNodeTypes,
    {
      id: "cultivator",
      description: "具有人格、有限视角、身体、神魂与修炼状态的行动者；境界不会替代心理、经历、关系和利益。",
      worldSpecific: true,
      fields: [
        ...personType.fields,
        { id: "lifespan-limit", valueType: "number", required: true, causal: true, unit: "year" },
        { id: "cultivation-stage", valueType: "string", required: true, causal: true },
        { id: "spiritual-root", valueType: "string", required: true, causal: true },
        { id: "meridian-state", valueType: "json", required: true, causal: true },
        { id: "dao-heart", valueType: "json", required: true, causal: true },
        { id: "qi-reserve", valueType: "number", required: true, causal: true, unit: "qi-unit" },
        { id: "karmic-obligations", valueType: "json", required: true, causal: true },
      ],
    },
    {
      id: "spirit-vein",
      description: "具有空间位置、灵气储量、再生、属性与稳定度的地脉系统，而不是无限法力背景。",
      worldSpecific: true,
      fields: [
        { id: "name", valueType: "string", required: true, causal: false },
        { id: "qi-capacity", valueType: "number", required: true, causal: true, unit: "qi-unit" },
        { id: "qi-reserve", valueType: "number", required: true, causal: true, unit: "qi-unit" },
        { id: "renewal-rate", valueType: "number", required: true, causal: true, unit: "qi-unit-per-year" },
        { id: "alignment", valueType: "string", required: true, causal: true },
        { id: "stability", valueType: "number", required: true, causal: true, unit: "index" },
        { id: "renewal-regime", valueType: "string", required: true, causal: true },
      ],
    },
    {
      id: "cultivation-art",
      description: "有传承、适配条件、成本和失败方式的修炼体系；功法文本与实际修行传统可分离。",
      worldSpecific: true,
      fields: [
        { id: "name", valueType: "string", required: true, causal: false },
        { id: "grade", valueType: "string", required: true, causal: true },
        { id: "lineage", valueType: "string", required: true, causal: true },
        { id: "prerequisites", valueType: "json", required: true, causal: true },
        { id: "costs", valueType: "json", required: true, causal: true },
        { id: "failure-modes", valueType: "json", required: true, causal: true },
      ],
    },
    {
      id: "dao-oath",
      description: "带有参与方、条款、见证、触发与执行边界的超凡承诺。",
      worldSpecific: true,
      fields: [
        { id: "name", valueType: "string", required: true, causal: false },
        { id: "clauses", valueType: "json", required: true, causal: true },
        { id: "witnesses", valueType: "json", required: true, causal: true },
        { id: "trigger", valueType: "string", required: true, causal: true },
        { id: "enforcement-mode", valueType: "string", required: true, causal: true },
        { id: "active", valueType: "boolean", required: true, causal: true },
      ],
    },
    {
      id: "realm-gate-remnant",
      description: "古代跨域构造的残存节点；其封印、泄漏和周期共振必须显式进入灵脉与灾害因果。",
      worldSpecific: true,
      fields: [
        { id: "name", valueType: "string", required: true, causal: false },
        { id: "status", valueType: "string", required: true, causal: true },
        { id: "annual-leakage", valueType: "number", required: true, causal: true, unit: "qi-unit-per-year" },
        { id: "resonance-period", valueType: "number", required: true, causal: true, unit: "year" },
        { id: "seal-integrity", valueType: "number", required: true, causal: true, unit: "index" },
      ],
    },
  ],
  edgeTypes: [
    ...commonEdgesFor(["cultivator"], ["spirit-vein", "realm-gate-remnant"], ["spirit-vein", "cultivation-art", "dao-oath", "realm-gate-remnant"]),
    { id: "draws-from", description: "从一条灵脉取得有配额、有成本的灵气流。", fromTypes: ["cultivator", "organization", "settlement"], toTypes: ["spirit-vein"], fields: [{ id: "annual-quota", valueType: "number", required: true, causal: true, unit: "qi-unit-per-year" }], worldSpecific: true },
    { id: "practices", description: "修士对功法的实际修习关系。", fromTypes: ["cultivator"], toTypes: ["cultivation-art"], fields: [{ id: "proficiency", valueType: "number", required: true, causal: true, unit: "index" }, { id: "interpretation", valueType: "string", required: false, causal: true }], worldSpecific: true },
    { id: "lineage-holds", description: "组织对功法谱系和传授权限的实际控制。", fromTypes: ["organization"], toTypes: ["cultivation-art"], fields: [{ id: "access-level", valueType: "string", required: true, causal: true }], worldSpecific: true },
    { id: "master-disciple", description: "方向明确、义务不对称且可能变化的师徒关系。", fromTypes: ["cultivator"], toTypes: ["cultivator"], fields: [{ id: "status", valueType: "string", required: true, causal: true }, { id: "obligations", valueType: "json", required: true, causal: true }, { id: "trust", valueType: "number", required: false, causal: true, unit: "index" }], worldSpecific: true },
    { id: "bound-by-oath", description: "某个主体作为明确角色受一份道誓约束。", fromTypes: ["cultivator", "organization", "institution"], toTypes: ["dao-oath"], fields: [{ id: "role", valueType: "string", required: true, causal: true }], worldSpecific: true },
    { id: "flows-to", description: "灵脉向可使用灵气存量形成有损耗的流。", fromTypes: ["spirit-vein"], toTypes: ["resource-stock"], fields: [{ id: "annual-flow", valueType: "number", required: true, causal: true, unit: "qi-unit-per-year" }, { id: "efficiency", valueType: "number", required: true, causal: true, unit: "ratio" }], worldSpecific: true },
    { id: "perturbs", description: "残存域门以声明的方式和周期扰动一条灵脉。", fromTypes: ["realm-gate-remnant"], toTypes: ["spirit-vein"], fields: [{ id: "mode", valueType: "string", required: true, causal: true }, { id: "stability-penalty", valueType: "number", required: true, causal: true, unit: "index" }], worldSpecific: true },
  ],
  rules: [
    { id: "rule.qi-is-local-and-accounted", description: "灵气是有位置、储量、流量、再生和损耗的因果资源；叙述不能凭空增加可用灵气。", invariant: true, provenance: ["source:premise"], enforcement: [
      { kind: "field-write-authority", nodeTypes: ["spirit-vein"], fieldId: "qi-reserve", mechanismIds: ["mechanism.spirit-vein-circulation"] },
      { kind: "field-write-authority", nodeTypes: ["resource-stock"], fieldId: "quantity", mechanismIds: ["mechanism.resource-balance", "mechanism.hazard-impact"] },
      { kind: "numeric-range", nodeTypes: ["spirit-vein"], fieldId: "qi-reserve", minimum: 0, maximumFieldId: "qi-capacity" },
      { kind: "numeric-range", nodeTypes: ["resource-stock"], fieldId: "quantity", minimum: 0, maximumFieldId: "capacity" },
    ] },
    { id: "rule.breakthrough-needs-preconditions", description: "境界突破必须引用功法适配、灵气、经脉、经验与道心条件，并保留失败和代价路径。", invariant: true, provenance: ["source:cultivation"], enforcement: [{ kind: "field-write-authority", nodeTypes: ["cultivator"], fieldId: "cultivation-stage", mechanismIds: ["mechanism.cultivation-breakthrough"] }] },
    { id: "rule.power-has-reach-and-counterplay", description: "术法与神识受距离、媒介、消耗、认知和反制约束；高境界不等于全知或无限权能。", invariant: true, provenance: ["source:cultivation"] },
    { id: "rule.tribulation-is-conditional-hazard", description: "天劫只由已声明条件触发，后果取决于强度、暴露、防护与应对，而不是随机剧情惩罚。", invariant: true, provenance: ["source:cultivation"] },
    { id: "rule.soul-continuity-is-explicit", description: "转世、夺舍、分魂、化身和记忆继承必须声明各自的人格、神魂、肉身与社会身份连续性。", invariant: true, provenance: ["source:cultivation"] },
    { id: "rule.dao-oath-is-scoped", description: "道誓只能检查声明的条款、证据和参与方，不能追溯未知事实、读取思想或扩大惩罚范围。", invariant: true, provenance: ["source:cultivation", "source:society"] },
    { id: "rule.sect-charter-is-not-practice", description: "宗门使命、长老立场、执事激励、弟子认知、实际执行与后果分别记录。", invariant: true, provenance: ["source:society"] },
    { id: "rule.mortals-remain-causal-actors", description: "凡人通过生产、税赋、迁徙、军役、信仰、市场与集体行动持续影响世界，不能被聚合成无意志背景。", invariant: true, provenance: ["source:society"] },
    { id: "rule.realm-gate-resonance-is-explicit", description: "残存域门的常态泄漏、共振周期、稳定度影响与灾害资格必须分别记录；残门存在本身不自动造成灵气损失。", invariant: true, provenance: ["source:causal-defaults"] },
    { id: "rule.spirit-vein-renewal-has-hysteresis", description: "主脉稳定度低于50只改变下一完整年度的再生档位；恢复到55以上并持续一年后再生能力才逐年恢复，禁止同一事件内瞬时反复切换。", invariant: true, provenance: ["source:causal-defaults"], enforcement: [{ kind: "field-write-authority", nodeTypes: ["spirit-vein"], fieldId: "renewal-rate", mechanismIds: ["mechanism.spirit-vein-circulation"] }] },
    { id: "rule.hazard-damage-follows-exposure-paths", description: "灵潮逆涌分别沿资源、灵脉、修士和聚落暴露路径结算，目标类型、脆弱度与防护决定不同后果，不能广播一个无差别伤害值。", invariant: true, provenance: ["source:causal-defaults"], enforcement: [{ kind: "action-requires-edge", mechanismId: "mechanism.hazard-impact", targetNodeTypes: ["resource-stock", "spirit-vein", "cultivator", "settlement"], edgeType: "exposed-to", direction: "from-target" }] },
    { id: "rule.bounded-lives-and-stability", description: "人口、修士灵气与灵脉稳定度不能越过声明的物理边界。", invariant: true, provenance: ["framework:executable-invariants-v1"], enforcement: [
      { kind: "numeric-range", nodeTypes: ["settlement", "population-group"], fieldId: "population", minimum: 0 },
      { kind: "numeric-range", nodeTypes: ["cultivator"], fieldId: "qi-reserve", minimum: 0 },
      { kind: "numeric-range", nodeTypes: ["spirit-vein"], fieldId: "stability", minimum: 0, maximum: 100 },
      { kind: "numeric-range", nodeTypes: ["place"], fieldId: "environmental-stress", minimum: 0, maximum: 100 },
    ] },
  ],
  mechanisms: [
    { id: "mechanism.resource-balance", version: "1", parameters: { conservation: "local-with-declared-renewal" } },
    { id: "mechanism.world-evolution", version: "1", parameters: {} },
    { id: "mechanism.environment-cycle", version: "1", parameters: { supernaturalEcology: true } },
    { id: "mechanism.route-dynamics", version: "1", parameters: { portalsRemainExplicit: true } },
    { id: "mechanism.population-dynamics", version: "1", parameters: { mortalsRemainCausal: true } },
    { id: "mechanism.exchange-network", version: "1", parameters: { qiAndMaterialMarketsSeparated: true } },
    { id: "mechanism.actor-deliberation", version: "1", parameters: { proposer: "deterministic", psychology: "parameterized-human-and-cultivator" } },
    { id: "mechanism.organization-adaptation", version: "1", parameters: { layeredJurisdiction: true } },
    { id: "mechanism.institution-adaptation", version: "1", parameters: { layeredJurisdiction: true } },
    { id: "mechanism.information-diffusion", version: "1", parameters: { supernaturalPerceptionStillBounded: true } },
    { id: "mechanism.relationship-dynamics", version: "1", parameters: { asymmetricObligations: true } },
    { id: "mechanism.conflict-dynamics", version: "1", parameters: { mortalAndCultivatorClaimsInteract: true } },
    { id: "mechanism.hazard-impact", version: "1", parameters: { stochasticHazards: true, supernaturalHazardsNeedDeclaredTriggers: true } },
    { id: "mechanism.spirit-vein-circulation", version: "1", parameters: { accountingUnit: "qi-unit", topology: "local-network" } },
    { id: "mechanism.cultivation-breakthrough", version: "1", parameters: { proposer: "deterministic", deterministicValidation: true } },
    { id: "mechanism.sect-lineage-governance", version: "1", parameters: { separateCharterFromPractice: true } },
    { id: "mechanism.dao-oath-consequence", version: "1", parameters: { strictDeclaredScope: true } },
  ],
  initialGraph: {
    nodes: [
      { id: "place:canglan-domain", type: "place", attributes: { name: "苍澜域", terrain: "三列云岭夹持苍澜河谷，古域门残基散布北麓", climate: "东南季雨、北岭长雪，灵潮每十二年偏转一次", "environmental-stress": 34, "carrying-capacity": 4200000, accessibility: 57 } },
      { id: "place:yunmeng-border", type: "place", attributes: { name: "云梦域西缘", terrain: "雾泽与悬桥相接的跨域边界", climate: "多雾、多雨，灵禽迁徙频繁", "environmental-stress": 29, "carrying-capacity": 860000, accessibility: 49 } },
      { id: "settlement:lingxi-market", type: "settlement", attributes: { name: "灵溪坊", population: 18600, "founded-year": 247, role: "宗门、王朝与山民之间的灵材、粮运和消息交换节点", "infrastructure-state": "南渠、仓栈与护坊阵正常运转", "food-security": 66, "migration-pressure": 29 } },
      { id: "resource:ambient-qi", type: "resource-stock", attributes: { name: "苍澜域可用灵气", quantity: 7200, "access-regime": "分脉约配额、宗门阵法截流与坊市灵石折算并存", capacity: 9000, "renewal-rate": 0, "baseline-demand": 0, scarcity: 0.2, "price-index": 108 } },
      { id: "route:canglan-yunmeng-road", type: "route", attributes: { name: "苍云古道", origin: "place:canglan-domain", destination: "place:yunmeng-border", capacity: 58, reliability: 61, "travel-time": 11, maintenance: 55, status: "open-with-risk" } },
      { id: "population:canglan-river-farmers", type: "population-group", attributes: { name: "苍澜河谷农户与舟民", population: 126000, livelihood: "水田、舟运、堤渠与坊市供给", "current-place": "place:canglan-domain", mobility: 28, cohesion: 54, "settlement-readiness": 38 } },
      { id: "spirit-vein:azure-river", type: "spirit-vein", attributes: { name: "苍澜主脉", "qi-capacity": 12000, "qi-reserve": 6840, "renewal-rate": 310, alignment: "水木为主、少量雷性", stability: 61, "renewal-regime": "稳定度不低于50；当前年再生310" } },
      { id: "cultivator:shen-qingluo", type: "cultivator", attributes: { name: "沈清洛", age: 27, traits: { openness: 68, conscientiousness: 82, extraversion: 34, agreeableness: 57, neuroticism: 49 }, wants: ["查清灵脉衰减", "取得独立勘脉资格"], fears: ["证据牵连师父", "苍澜百姓为宗门扩招付出代价"], needs: ["把忠诚与服从分开", "让判断经得起他人复核"], beliefs: ["秩序只有可被追责才值得维护", "师门之恩不应成为遮蔽事实的理由"], narrative: "我想守住的不是宗门颜面，而是它曾经许下的责任。", memories: ["玄历六〇七年陆玄机在雪崩中救她", "玄历六一一年首次听见主脉逆响"], stress: 46, agency: 58, "current-plan": "复核主脉回声与勘脉账册", "lifespan-limit": 180, "cultivation-stage": "筑基初期", "spiritual-root": "水木双灵根", "meridian-state": { integrity: 78, hiddenInjury: "left-hand taiyin channel" }, "dao-heart": { commitment: "可验证的守护", conflict: "师恩与公共后果" }, "qi-reserve": 74, "karmic-obligations": ["师徒救命之恩", "勘脉司保密令", "灵溪坊旧友请求"] } },
      { id: "cultivator:lu-xuanji", type: "cultivator", attributes: { name: "陆玄机", age: 164, traits: { openness: 45, conscientiousness: 88, extraversion: 61, agreeableness: 39, neuroticism: 26 }, wants: ["维持太玄剑宗在苍澜域的主导权", "在自己寿尽前完成护域阵"], fears: ["宗门分裂", "旧年封存决定被解释为私利"], needs: ["承认短期稳定也可能制造长期脆弱"], beliefs: ["只有强宗门才能阻止九域再乱", "不完整的真相有时比公开恐慌更少伤亡"], narrative: "我替后来人背下他们无力承担的选择。", memories: ["天衡残门暴走", "玄历五九三年分脉约谈判"], stress: 39, agency: 77, "current-plan": "维持封存并优先完成护域阵", "lifespan-limit": 220, "cultivation-stage": "金丹后期", "spiritual-root": "金水双灵根", "meridian-state": { integrity: 63, hiddenInjury: "core fissure" }, "dao-heart": { commitment: "以秩序抵御崩裂", conflict: "保护与控制" }, "qi-reserve": 430, "karmic-obligations": ["护域阵死者", "太玄剑宗长老席", "沈清洛师徒因果"] } },
      { id: "organization:taixuan-sword-sect", type: "organization", attributes: { name: "太玄剑宗", "declared-goal": "守护苍澜灵脉并镇守北麓残门", "actual-practice": "以护域责任换取优先配额，同时维持扩招和内门峰系竞争", resources: ["护域阵", "三千六百弟子名籍", "灵脉勘测档案", "剑诀传承"], culture: ["功绩公开排序", "师承责任", "对外守土叙事"], "internal-coalitions": ["护域保守派", "开脉扩张派", "外门改革派"], legitimacy: 68, cohesion: 59, capacity: 81, status: "active" } },
      { id: "organization:great-sheng-court", type: "organization", attributes: { name: "大晟苍澜道署", "declared-goal": "保境安民并监督分脉约", "actual-practice": "依赖宗门处理超凡风险，以粮运、户籍和道路控制换取有限审计权", resources: ["户籍", "粮仓", "驿道", "两营凡军", "巡灵使印"], culture: ["文书合法性", "风险外包", "地方关系网"], "internal-coalitions": ["巡灵使系统", "地方豪族", "京派监司"], legitimacy: 55, cohesion: 51, capacity: 62, status: "active" } },
      { id: "organization:lingxi-guild", type: "organization", attributes: { name: "灵溪坊商盟", "declared-goal": "维持公开交换与跨辖区履约", "actual-practice": "以价格、赊账和消息差控制小宗门与散修的进入机会", resources: ["仓栈", "灵石票据", "驮队", "跨域耳目"], culture: ["契约优先", "风险分摊", "信息分层"], "internal-coalitions": ["灵材行", "粮商", "散修担保人"], legitimacy: 52, cohesion: 63, capacity: 72, status: "active" } },
      { id: "institution:azure-vein-covenant", type: "institution", attributes: { name: "苍澜分脉约", "formal-rule": "主脉年净抽取不得超过测定再生量七成，宗门、道署与坊市互查账册", "rule-in-use": "太玄剑宗先报阵法维护量，道署抽查滞后，商盟以折价灵石吸收超额需求", "enforcement-capacity": 58 } },
      { id: "art:clear-void-sword", type: "cultivation-art", attributes: { name: "清虚听潮剑经", grade: "地阶中品", lineage: "太玄剑宗听潮峰", prerequisites: ["水或金水灵根适配", "经脉完整度大于六成", "能分辨地脉回声"], costs: ["长期静听导致情绪迟滞", "突破时消耗大量水木灵气"], "failure-modes": ["误把阵法回响当作地脉真声", "剑意反灌太阴经"] } },
      { id: "oath:azure-nonexhaustion", type: "dao-oath", attributes: { name: "苍澜不竭誓", clauses: ["不得明知主脉净抽取超过约定仍签署无异报告", "只约束签署时可访问的勘测证据", "签署后故意阻断职责范围内依法应互查的证据，并据此提交无异结论，仍构成违誓"], witnesses: ["苍澜主脉祭坛", "太玄剑宗", "大晟苍澜道署"], trigger: "签署者在可核验证据下故意提交无异结论，或先故意阻断职责内证据再提交无异结论", "enforcement-mode": "七日内神识滞涩并留下可检测誓痕", active: true } },
      { id: "gate:tianheng-north-remnant", type: "realm-gate-remnant", attributes: { name: "北麓天衡残门", status: "玄历五七一年暴走后封闭，常态不通行", "annual-leakage": 0, "resonance-period": 12, "seal-integrity": 73 } },
      { id: "hazard:spirit-tide-reversal", type: "hazard", attributes: { name: "灵潮逆涌", kind: "supernatural-extreme-weather", "baseline-frequency": 5, "trigger-condition": "玄历年份可被12整除，且苍澜主脉稳定度低于65；满足条件只取得发生资格", "severity-basis": "主脉稳定度、残门封印完整度、目标暴露和防护能力" } },
    ],
    edges: [
      { id: "edge:lingxi-in-canglan", type: "located-in", from: "settlement:lingxi-market", to: "place:canglan-domain", attributes: {} },
      { id: "edge:ambient-qi-in-canglan", type: "located-in", from: "resource:ambient-qi", to: "place:canglan-domain", attributes: {} },
      { id: "edge:vein-in-canglan", type: "located-in", from: "spirit-vein:azure-river", to: "place:canglan-domain", attributes: {} },
      { id: "edge:qingluo-in-canglan", type: "located-in", from: "cultivator:shen-qingluo", to: "place:canglan-domain", attributes: {} },
      { id: "edge:xuanji-in-canglan", type: "located-in", from: "cultivator:lu-xuanji", to: "place:canglan-domain", attributes: {} },
      { id: "edge:taixuan-in-canglan", type: "located-in", from: "organization:taixuan-sword-sect", to: "place:canglan-domain", attributes: {} },
      { id: "edge:court-in-canglan", type: "located-in", from: "organization:great-sheng-court", to: "place:canglan-domain", attributes: {} },
      { id: "edge:guild-in-canglan", type: "located-in", from: "organization:lingxi-guild", to: "place:canglan-domain", attributes: {} },
      { id: "edge:covenant-in-canglan", type: "located-in", from: "institution:azure-vein-covenant", to: "place:canglan-domain", attributes: {} },
      { id: "edge:gate-in-canglan", type: "located-in", from: "gate:tianheng-north-remnant", to: "place:canglan-domain", attributes: {} },
      { id: "edge:reversal-in-canglan", type: "located-in", from: "hazard:spirit-tide-reversal", to: "place:canglan-domain", attributes: {} },
      { id: "edge:river-farmers-in-canglan", type: "located-in", from: "population:canglan-river-farmers", to: "place:canglan-domain", attributes: {} },
      { id: "edge:qingluo-taixuan", type: "member-of", from: "cultivator:shen-qingluo", to: "organization:taixuan-sword-sect", attributes: { role: "听潮峰勘脉弟子" } },
      { id: "edge:xuanji-taixuan", type: "member-of", from: "cultivator:lu-xuanji", to: "organization:taixuan-sword-sect", attributes: { role: "听潮峰主兼护域阵监" } },
      { id: "edge:xuanji-qingluo", type: "master-disciple", from: "cultivator:lu-xuanji", to: "cultivator:shen-qingluo", attributes: { status: "公开承认的亲传师徒", obligations: ["传法与护持", "服从合理师命", "不得代替对方承担道誓"], trust: 71 } },
      { id: "edge:qingluo-practices-clear-void", type: "practices", from: "cultivator:shen-qingluo", to: "art:clear-void-sword", attributes: { proficiency: 46, interpretation: "以听辨和校验优先于斩击" } },
      { id: "edge:taixuan-holds-clear-void", type: "lineage-holds", from: "organization:taixuan-sword-sect", to: "art:clear-void-sword", attributes: { "access-level": "内门与获准勘脉者" } },
      { id: "edge:taixuan-governs-vein", type: "governs", from: "organization:taixuan-sword-sect", to: "spirit-vein:azure-river", attributes: { basis: "分脉约授予的护域和阵法维护权" } },
      { id: "edge:covenant-governs-vein", type: "governs", from: "institution:azure-vein-covenant", to: "spirit-vein:azure-river", attributes: { basis: "年净抽取上限与三方互查条款" } },
      { id: "edge:taixuan-draws-vein", type: "draws-from", from: "organization:taixuan-sword-sect", to: "spirit-vein:azure-river", attributes: { "annual-quota": 190 } },
      { id: "edge:lingxi-draws-vein", type: "draws-from", from: "settlement:lingxi-market", to: "spirit-vein:azure-river", attributes: { "annual-quota": 38 } },
      { id: "edge:vein-flows-ambient", type: "flows-to", from: "spirit-vein:azure-river", to: "resource:ambient-qi", attributes: { "annual-flow": 120, efficiency: 0.82 } },
      { id: "edge:gate-perturbs-vein", type: "perturbs", from: "gate:tianheng-north-remnant", to: "spirit-vein:azure-river", attributes: { mode: "每十二年共振期降低稳定度，不产生常态泄漏", "stability-penalty": 9 } },
      { id: "edge:taixuan-bound-oath", type: "bound-by-oath", from: "organization:taixuan-sword-sect", to: "oath:azure-nonexhaustion", attributes: { role: "护域签署方" } },
      { id: "edge:court-bound-oath", type: "bound-by-oath", from: "organization:great-sheng-court", to: "oath:azure-nonexhaustion", attributes: { role: "监督签署方" } },
      { id: "edge:covenant-bound-oath", type: "bound-by-oath", from: "institution:azure-vein-covenant", to: "oath:azure-nonexhaustion", attributes: { role: "条款载体" } },
      { id: "edge:lingxi-reversal-exposure", type: "exposed-to", from: "settlement:lingxi-market", to: "hazard:spirit-tide-reversal", attributes: { vulnerability: 47 } },
      { id: "edge:qingluo-reversal-exposure", type: "exposed-to", from: "cultivator:shen-qingluo", to: "hazard:spirit-tide-reversal", attributes: { vulnerability: 36 } },
      { id: "edge:ambient-reversal-exposure", type: "exposed-to", from: "resource:ambient-qi", to: "hazard:spirit-tide-reversal", attributes: { vulnerability: 58 } },
      { id: "edge:vein-reversal-exposure", type: "exposed-to", from: "spirit-vein:azure-river", to: "hazard:spirit-tide-reversal", attributes: { vulnerability: 69 } },
      { id: "edge:guild-court-trade", type: "trades-with", from: "organization:lingxi-guild", to: "organization:great-sheng-court", attributes: { capacity: 68, reliability: 63, "price-spread": 114 } },
      { id: "edge:taixuan-court-relation", type: "related-to", from: "organization:taixuan-sword-sect", to: "organization:great-sheng-court", attributes: { relation: "共同治理、互相依赖且争夺审计解释权", trust: 44 } },
    ],
    facts: [
      { id: "fact:qi-local-accounting", subjectId: "spirit-vein:azure-river", predicate: "causal-resource-regime", value: "local-stock-flow-with-renewal-and-loss", authority: "creator-confirmed", provenance: ["source:premise"], epistemicScope: "world" },
      { id: "fact:current-xuan-year", subjectId: "place:canglan-domain", predicate: "current-calendar-year", value: 612, authority: "creator-confirmed", provenance: ["source:people", "source:causal-defaults"], epistemicScope: "world" },
      { id: "fact:vein-accounting-baseline", subjectId: "spirit-vein:azure-river", predicate: "annual-full-quota-net-change", value: { renewal: 310, declaredQuotaCeiling: 228, ecologicalAndAmbientOutflow: 120, net: -38, unit: "qi-unit-per-year" }, authority: "creator-confirmed", provenance: ["source:causal-defaults"], epistemicScope: "world" },
      { id: "fact:gate-resonance-eligibility", subjectId: "gate:tianheng-north-remnant", predicate: "current-resonance-state", value: { year: 612, resonanceEligible: true, continuousLeakage: false }, authority: "creator-confirmed", provenance: ["source:causal-defaults"], epistemicScope: "world" },
      { id: "fact:renewal-threshold-contract", subjectId: "spirit-vein:azure-river", predicate: "stability-renewal-coupling", value: { thresholdBelow: 50, nextYearRenewal: 210, recoveryThreshold: 55, recoveryDelayYears: 1, annualRecoveryStep: 25 }, authority: "creator-confirmed", provenance: ["source:causal-defaults"], epistemicScope: "world" },
      { id: "fact:vein-decline-observed", subjectId: "spirit-vein:azure-river", predicate: "twenty-year-reserve-trend", value: { direction: "declining", confidence: "high", publicConsensus: false }, authority: "creator-confirmed", provenance: ["source:people"], epistemicScope: "world" },
      { id: "fact:sect-goal-practice-gap", subjectId: "organization:taixuan-sword-sect", predicate: "mission-practice-gap", value: true, authority: "creator-confirmed", provenance: ["source:society", "source:people"], epistemicScope: "world" },
      { id: "fact:oath-scope-limited", subjectId: "oath:azure-nonexhaustion", predicate: "cannot-read-unknown-intent", value: true, authority: "creator-confirmed", provenance: ["source:cultivation"], epistemicScope: "world" },
      { id: "fact:qingluo-heard-reversal", subjectId: "cultivator:shen-qingluo", predicate: "accessible-observation", value: "主脉回声与宗门上报的稳定曲线不一致", authority: "creator-confirmed", provenance: ["source:people"], epistemicScope: ["cultivator:shen-qingluo"] },
    ],
  },
  presentationHints: {
    mapStyle: "large-format Chinese shanshui atlas with nine clearly separated domains, readable terrain and no label overlap",
    artStyle: "ink, mineral pigment and restrained gold xianxia setting-book plates",
    palette: "azurite, pine green, ink black, cloud white, muted gold",
    focusRegion: "苍澜域",
  },
};
